# Generated by Django 6.0.2 on 2026-04-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('block_type', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('elements', models.CharField(blank=True, max_length=100)),
                ('diameter', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, default='Evident', max_length=200)),
                ('platform', models.CharField(blank=True, max_length=200)),
                ('model', models.CharField(blank=True, max_length=200)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SensitivityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('material', models.CharField(blank=True, max_length=200)),
                ('block_type', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
