# Generated by Django 6.0.2 on 2026-04-28 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_encoder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encoder',
            old_name='resolution',
            new_name='step_count',
        ),
    ]
