# Generated by Django 6.0.2 on 2026-04-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_rename_resolution_encoder_step_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='platform',
        ),
        migrations.AddField(
            model_name='scope',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scope',
            name='calibration_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scope',
            name='software',
            field=models.CharField(blank=True, default='OmniPC', max_length=200),
        ),
        migrations.AddField(
            model_name='scope',
            name='software_version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
