# Generated by Django 6.0.2 on 2026-10-01 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_remove_scope_platform_scope_calibration_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProbeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('series', models.CharField(blank=True, help_text='Housing / series, e.g. A1, A32.', max_length=50)),
                ('manufacturer', models.CharField(blank=True, default='Evident', max_length=100)),
                ('item_number', models.CharField(blank=True, max_length=50)),
                ('frequency', models.FloatField(blank=True, help_text='MHz', null=True)),
                ('elements', models.PositiveIntegerField(blank=True, null=True)),
                ('pitch', models.FloatField(blank=True, help_text='Element pitch, mm', null=True)),
                ('aperture', models.FloatField(blank=True, help_text='Active aperture, mm', null=True)),
                ('elevation', models.FloatField(blank=True, help_text='Element width (elevation), mm', null=True)),
                ('length', models.FloatField(blank=True, help_text='Housing length, mm', null=True)),
                ('width', models.FloatField(blank=True, help_text='Housing width, mm', null=True)),
                ('height', models.FloatField(blank=True, help_text='Housing height, mm', null=True)),
                ('source', models.CharField(blank=True, help_text='Datasheet or catalogue the specs come from.', max_length=300)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['series', 'model'],
            },
        ),
        migrations.CreateModel(
            name='WedgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, unique=True)),
                ('probe_series', models.CharField(blank=True, help_text='Probe series it fits, e.g. A1.', max_length=50)),
                ('manufacturer', models.CharField(blank=True, default='Evident', max_length=100)),
                ('refracted_angle', models.FloatField(blank=True, help_text='Nominal refracted angle in steel, °', null=True)),
                ('wave_type', models.CharField(blank=True, choices=[('SW', 'Shear'), ('LW', 'Longitudinal')], max_length=2)),
                ('sweep', models.CharField(blank=True, help_text='Recommended sweep, e.g. 40 to 70°', max_length=50)),
                ('length', models.FloatField(blank=True, help_text='mm', null=True)),
                ('width', models.FloatField(blank=True, help_text='mm', null=True)),
                ('width_wings', models.FloatField(blank=True, help_text='Width with scanner wings, mm', null=True)),
                ('height', models.FloatField(blank=True, help_text='mm', null=True)),
                ('wedge_angle', models.FloatField(blank=True, help_text='Probe face angle, °', null=True)),
                ('velocity', models.FloatField(blank=True, help_text='Wedge material velocity, m/s', null=True)),
                ('first_element_height', models.FloatField(blank=True, help_text='Height to the first element centre, mm', null=True)),
                ('primary_offset', models.FloatField(blank=True, help_text='Wedge front to the first element centre along the scan axis, mm (negative = behind the front face, as OmniScan shows it).', null=True)),
                ('source', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['probe_series', 'model'],
            },
        ),
        migrations.AlterModelOptions(
            name='sensitivityblock',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='bevel_geometry',
            field=models.CharField(blank=True, help_text='e.g. 37 degrees', max_length=100),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='cal_diameter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cal. diameter'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='cal_sch_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Sch / nom. thk'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='cal_thickness',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cal. thickness'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='couplant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='encoder',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='encoder_steps',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='pipe_size',
            field=models.CharField(blank=True, help_text='e.g. 6in Sch 40', max_length=100, verbose_name='NPS / Sch'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='reflector_depth',
            field=models.CharField(blank=True, max_length=50, verbose_name='Notch / SDH depth'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='scan_res',
            field=models.CharField(blank=True, max_length=50, verbose_name='Scan res.'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='scan_speed',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='surface_cal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Surface (cal.)'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='surface_test',
            field=models.CharField(blank=True, max_length=100, verbose_name='Surface (test)'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='temperature',
            field=models.CharField(blank=True, max_length=50, verbose_name='Temp (°F)'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='test_diameter',
            field=models.CharField(blank=True, max_length=50, verbose_name='Test diameter'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='test_sch_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Test Sch / nom. thk'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='test_thickness',
            field=models.CharField(blank=True, max_length=50, verbose_name='Test thickness'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='velocity_long',
            field=models.CharField(blank=True, max_length=50, verbose_name='L-wave velocity'),
        ),
        migrations.AddField(
            model_name='sensitivityblock',
            name='velocity_shear',
            field=models.CharField(blank=True, help_text='e.g. 0.128 in/µs', max_length=50, verbose_name='Shear velocity'),
        ),
        migrations.AlterField(
            model_name='sensitivityblock',
            name='block_type',
            field=models.CharField(blank=True, help_text='e.g. Notch, SDH', max_length=200),
        ),
        migrations.AlterField(
            model_name='sensitivityblock',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, verbose_name='Cal Std. #'),
        ),
        migrations.AddField(
            model_name='probe',
            name='catalogue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='probes', to='equipment.probemodel', verbose_name='Catalogue model'),
        ),
    ]
