# Generated by Django 6.0.2 on 2026-10-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_seed_catalogues'),
    ]

    operations = [
        migrations.AddField(
            model_name='wedgemodel',
            name='bottom_face',
            field=models.CharField(blank=True, help_text='Flat, AOD, COD, AID, …', max_length=20),
        ),
        migrations.AddField(
            model_name='wedgemodel',
            name='part_diameter',
            field=models.FloatField(blank=True, help_text='Diameter the curved face fits, mm', null=True),
        ),
        migrations.AddField(
            model_name='wedgemodel',
            name='probe_fit',
            field=models.CharField(blank=True, help_text='Probe this geometry is for, e.g. 10L32 or 5/10L32 (from the library name).', max_length=100),
        ),
        migrations.AddField(
            model_name='wedgemodel',
            name='roof_angle',
            field=models.FloatField(blank=True, help_text='°', null=True),
        ),
        migrations.AddField(
            model_name='wedgemodel',
            name='secondary_offset',
            field=models.FloatField(blank=True, help_text='Wedge side to the element centre, mm', null=True),
        ),
    ]
