# Generated by Django 6.0.2 on 2026-10-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_clear_sa1_first_element_height'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='probemodel',
            options={'ordering': ['series', 'frequency', 'elements', 'model']},
        ),
    ]
