# Generated by Django 6.0.2 on 2026-10-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_probe_model_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='probe',
            name='calibration_obtainable',
            field=models.BooleanField(blank=True, null=True, verbose_name='Calibration obtainable'),
        ),
        migrations.AddField(
            model_name='probe',
            name='defective_elements',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Defective elements'),
        ),
        migrations.AddField(
            model_name='probe',
            name='inactive_elements',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Inactive elements'),
        ),
        migrations.AddField(
            model_name='probe',
            name='previous_defective_elements',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Previous defective elements'),
        ),
        migrations.AddField(
            model_name='probe',
            name='previous_inactive_elements',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Previous inactive elements'),
        ),
        migrations.AddField(
            model_name='scope',
            name='instrument_software_version',
            field=models.CharField(blank=True, help_text="The unit's own software, e.g. 5.20.0 or MXU 4.4R4.", max_length=100, verbose_name='Instrument software version'),
        ),
        migrations.AddField(
            model_name='scope',
            name='module_cal_due',
            field=models.DateField(blank=True, null=True, verbose_name='Module cal. due'),
        ),
        migrations.AddField(
            model_name='scope',
            name='module_model',
            field=models.CharField(blank=True, max_length=200, verbose_name='Module / pulser model'),
        ),
        migrations.AddField(
            model_name='scope',
            name='module_serial',
            field=models.CharField(blank=True, max_length=200, verbose_name='Module S/N'),
        ),
        migrations.AddField(
            model_name='scope',
            name='name',
            field=models.CharField(blank=True, help_text='As the report names it, e.g. Omniscan X3.', max_length=200, verbose_name='Unit'),
        ),
        migrations.AddField(
            model_name='scope',
            name='scanner_type',
            field=models.CharField(blank=True, help_text='e.g. SAUT', max_length=100),
        ),
        migrations.AlterField(
            model_name='scope',
            name='software',
            field=models.CharField(blank=True, default='OmniPC', max_length=200, verbose_name='Analysis software'),
        ),
        migrations.AlterField(
            model_name='scope',
            name='software_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Analysis software version'),
        ),
    ]
