# Generated by Django 6.0.2 on 2026-10-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_inventory_sheet_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibrationblock',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibrationblock',
            name='calibration_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calibrationblock',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Certificate number'),
        ),
        migrations.AddField(
            model_name='encoder',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encoder',
            name='calibration_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encoder',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Certificate number'),
        ),
        migrations.AddField(
            model_name='probe',
            name='calibration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probe',
            name='calibration_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='probe',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Certificate number'),
        ),
        migrations.AddField(
            model_name='scope',
            name='certificate_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Certificate number'),
        ),
    ]
