from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('create/', views.create_report, name='create-report'),
    path('setups/', views.setup_list, name='setup-list'),
    path('setups/new/', views.new_setup, name='new-setup'),
    path('setup/<int:pk>/edit/', views.edit_setup, name='edit-setup'),
    path('reports/', views.report_list, name='report-list'),
    path('reports/new/', views.new_report, name='new-report'),
    path('report/<int:pk>/generate/', views.generate_report, name='generate-report'),
    path('report/<int:pk>/preview/', views.preview_report, name='preview-report'),
    path('report/<int:pk>/docx/', views.report_docx, name='report-docx'),
    path('report/<int:pk>/pdf/', views.report_pdf, name='report-pdf'),
    path('reports/<int:pk>/edit/', views.edit_existing_report, name='edit-report'),
    path('nde/', views.nde_upload, name='nde-upload'),
    path('texts/', views.snippet_list, name='snippet-list'),
    path('texts/new/', views.new_snippet, name='new-snippet'),
    path('text/<int:pk>/edit/', views.edit_snippet, name='edit-snippet'),
    path('library/defaults/', views.defaults_list, name='defaults-list'),
    path('library/defaults/<str:report_type>/', views.edit_defaults, name='edit-defaults'),
    path('scan-plans/', views.scan_plan_list, name='scan-plan-list'),
    path('scan-plans/new/', views.new_scan_plan, name='new-scan-plan'),
    path('scan-plans/preview.png', views.scan_plan_preview, name='scan-plan-preview'),
    path('scan-plans/wedges.json', views.scan_plan_wedges, name='scan-plan-wedges'),
    path('scan-plans/wedge-data.json', views.scan_plan_wedge_data, name='scan-plan-wedge-data'),
    path('scan-plan/<int:pk>/edit/', views.edit_scan_plan, name='edit-scan-plan'),
    path('scan-plan/<int:pk>.png', views.scan_plan_png, name='scan-plan-png'),
]
