DOCUMENT_CONFIGS = {
    "long_form": {
        "template": "long_form_template.docx",
        "output": "long_form_output.docx",
        "LONG_FORM_FIELDS": [
            "document_title",
            "client",
            "location",
            "work_order",
            "project_number",
            "report_date",
            "test_date",
            "project_type",
            "procedure",
            "technician_name",
            "certification",
            "examination_scope",
            "executive_summary",
            "equipment_id",
            "equipment_overview",
            "work_scope",
            "x_axis_reference",
            "y_axis_reference",
            "ut_method",
        ],
        "SETUP_FIELDS": [
            "manufacturer",
            "scope_model",
            "x_res",
            "y_res",
            "transducer_model",
            "transducer_serial",
            "foc_depth",
            "wave_propogation",
            "freq",
            "elements",
            "cal_material",
            "scope_serial",
            "material_temp",
            "cal_block_type",
            "cal_block_serial",
            "surface_prep",
            "tr_min",
            "tr_max",
        ]
    }
}