# Generated by Django 6.0.2 on 2026-03-11 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_title', models.CharField(max_length=200)),
                ('client', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('work_order', models.CharField(max_length=100)),
                ('project_number', models.CharField(max_length=100)),
                ('report_date', models.DateField()),
                ('test_date', models.DateField()),
                ('project_type', models.CharField(max_length=200)),
                ('procedure', models.CharField(max_length=200)),
                ('technician_name', models.CharField(max_length=200)),
                ('certification', models.CharField(max_length=200)),
                ('examination_scope', models.TextField()),
                ('executive_summary', models.TextField()),
                ('equipment_id', models.CharField(max_length=200)),
                ('equipment_overview', models.TextField()),
                ('work_scope', models.TextField()),
                ('x_axis_reference', models.CharField(max_length=200)),
                ('y_axis_reference', models.CharField(max_length=200)),
                ('ut_method', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Setup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('scope_model', models.CharField(blank=True, max_length=200)),
                ('scope_serial', models.CharField(blank=True, max_length=200)),
                ('transducer_model', models.CharField(blank=True, max_length=200)),
                ('transducer_serial', models.CharField(blank=True, max_length=200)),
                ('foc_depth', models.CharField(blank=True, max_length=100)),
                ('wave_propogation', models.CharField(blank=True, max_length=100)),
                ('freq', models.CharField(blank=True, max_length=100)),
                ('elements', models.CharField(blank=True, max_length=100)),
                ('x_res', models.CharField(blank=True, max_length=100)),
                ('y_res', models.CharField(blank=True, max_length=100)),
                ('cal_material', models.CharField(blank=True, max_length=200)),
                ('material_temp', models.CharField(blank=True, max_length=50)),
                ('cal_block_type', models.CharField(blank=True, max_length=200)),
                ('cal_block_serial', models.CharField(blank=True, max_length=200)),
                ('surface_prep', models.CharField(blank=True, max_length=200)),
                ('tr_min', models.CharField(blank=True, max_length=50)),
                ('tr_max', models.CharField(blank=True, max_length=50)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='reports.report')),
            ],
        ),
    ]
