# Generated by Django 6.0.2 on 2026-03-12 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assistant_certification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='assistant_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
