# Generated by Django 6.0.2 on 2026-03-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_assistant_certification_report_assistant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='document_filename',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
