# Generated by Django 6.0.2 on 2026-03-20 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_certification_alter_report_client_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='wave_propogation',
            new_name='wave_propagation',
        ),
    ]
