# Generated by Django 6.0.2 on 2026-03-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_rename_wave_propagation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='document_filename',
            field=models.TextField(blank=True),
        ),
    ]
