# Generated by Django 6.0.2 on 2026-03-20 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_filename_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='document_filename',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='report',
            name='document_title',
            field=models.TextField(blank=True),
        ),
    ]
