# Generated by Django 6.0.2 on 2026-03-20 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_title_to_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setups', to='reports.report'),
        ),
    ]
