# Generated by Django 6.0.2 on 2026-04-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_setup_report_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='gain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='probe_diameter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='ref_gain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='scope_platform',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='sound_velocity',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='specimen_od',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='specimen_thickness',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='voltage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='wedge_angle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='wedge_model',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='manufacturer',
            field=models.CharField(blank=True, default='Evident', max_length=200),
        ),
        migrations.AlterField(
            model_name='setup',
            name='x_res',
            field=models.CharField(blank=True, default=0.039, max_length=100),
        ),
        migrations.AlterField(
            model_name='setup',
            name='y_res',
            field=models.CharField(blank=True, default=0.039, max_length=100),
        ),
    ]
