# Generated by Django 6.0.2 on 2026-04-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_setup_gain_setup_probe_diameter_setup_ref_gain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='scan_length',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='scan_width',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
