# Generated by Django 6.0.2 on 2026-04-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_setup_scan_length_setup_scan_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='x_res',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='setup',
            name='y_res',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
