# Generated by Django 6.0.2 on 2026-04-28 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_alter_setup_x_res_alter_setup_y_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='angle_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='angle_step',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
