# Generated by Django 5.2.8 on 2026-05-11 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_setup_angle_range_setup_angle_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultsTablePreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('columns', models.JSONField(default=list)),
            ],
        ),
        migrations.AddField(
            model_name='setup',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ResultsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.JSONField(default=list)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='results_table', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ResultsRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cells', models.JSONField(default=list)),
                ('order', models.IntegerField(default=0)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='reports.resultstable')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
