# Generated by Django 6.0.2 on 2026-09-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_type_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='acquisition_date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='active_elements',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='band_pass_filter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='beam_formation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='beam_gain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='calibrations',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='digitizing_frequency',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='element_aperture',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='element_step',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='encoder_resolution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='gates',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='pcs',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='pulse_width',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='scan_pattern',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='source_file',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='setup',
            name='specimen_dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
