# Generated by Django 6.0.2 on 2026-09-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_setup_nde_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportimage',
            name='kind',
            field=models.CharField(choices=[('scan', 'Scan image (photo summary)'), ('drawing', 'Equipment drawing')], default='scan', max_length=20),
        ),
        migrations.AddField(
            model_name='reportimage',
            name='scan_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
