# Generated by Django 6.0.2 on 2026-09-29 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_reportimage_kind_scan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='procedure',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SetupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='setup_images/')),
                ('order', models.IntegerField(default=0)),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.setup')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
