# Generated by Django 6.0.2 on 2026-09-29 18:41
# Reordered by hand: ReportPerson is created and filled from the old technician/assistant
# fields before those fields are removed.

import django.db.models.deletion
from django.db import migrations, models


def technicians_to_people(apps, schema_editor):
    """Technician -> prepared + examined by; assistant -> examined by."""
    Report = apps.get_model('reports', 'Report')
    ReportPerson = apps.get_model('reports', 'ReportPerson')
    people = []
    for report in Report.objects.all():
        order = 0
        if report.technician_name.strip():
            people.append(ReportPerson(report=report, name=report.technician_name.strip(),
                                       certification=report.certification, prepared=True, examined=True, order=order))
            order += 1
        if report.assistant_name.strip():
            people.append(ReportPerson(report=report, name=report.assistant_name.strip(),
                                       certification=report.assistant_certification, examined=True, order=order))
    ReportPerson.objects.bulk_create(people)


def people_to_technicians(apps, schema_editor):
    """Reverse: first two people back into technician / assistant."""
    Report = apps.get_model('reports', 'Report')
    for report in Report.objects.all():
        people = list(report.people.order_by('order', 'pk')[:2])
        if people:
            report.technician_name, report.certification = people[0].name, people[0].certification
        if len(people) > 1:
            report.assistant_name, report.assistant_certification = people[1].name, people[1].certification
        report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_setup_title_procedure_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('certification', models.CharField(blank=True, max_length=200)),
                ('prepared', models.BooleanField(default=False, verbose_name='Prepared by')),
                ('examined', models.BooleanField(default=False, verbose_name='Examined by')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed by')),
                ('order', models.IntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='reports.report')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.RunPython(technicians_to_people, people_to_technicians),
        migrations.RemoveField(
            model_name='report',
            name='assistant_certification',
        ),
        migrations.RemoveField(
            model_name='report',
            name='assistant_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='certification',
        ),
        migrations.RemoveField(
            model_name='report',
            name='technician_name',
        ),
        migrations.AddField(
            model_name='report',
            name='comparison_title',
            field=models.CharField(blank=True, default='DATA COMPARISON', max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='test_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='kind',
            field=models.CharField(choices=[('scan', 'Scan image (photo summary)'), ('drawing', 'Equipment drawing'), ('comparison', 'Data comparison')], default='scan', max_length=20),
        ),
    ]
