# Generated by Django 6.0.2 on 2026-09-29 18:50
# The data-comparison section was removed (job-specific content, added by hand when needed).

from django.db import migrations, models


def comparison_images_to_scan_images(apps, schema_editor):
    """Keep any saved comparison images as photo-summary images, labelled with their title."""
    ReportImage = apps.get_model('reports', 'ReportImage')
    ReportImage.objects.filter(kind='comparison').update(kind='scan')


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_personnel_test_end_comparison'),
    ]

    operations = [
        migrations.RunPython(comparison_images_to_scan_images, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='report',
            name='comparison_title',
        ),
        migrations.AlterField(
            model_name='reportimage',
            name='kind',
            field=models.CharField(choices=[('scan', 'Scan image (photo summary)'), ('drawing', 'Equipment drawing')], default='scan', max_length=20),
        ),
    ]
