# Generated by Django 6.0.2 on 2026-09-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_remove_data_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='asset_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='discussion',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('technique', 'Technique description'), ('discussion', 'Discussion')], default='technique', max_length=20)),
                ('name', models.CharField(help_text="Technique: the setup Technique title it applies to, e.g. HydroFORM. Discussion: 'default' is used for new reports.", max_length=100)),
                ('title', models.CharField(blank=True, help_text='Bold lead of the bullet, e.g. ENCODED HydroFORM 0-degree PAUT', max_length=200)),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'constraints': [models.UniqueConstraint(fields=('kind', 'name'), name='unique_snippet_kind_name')],
            },
        ),
    ]
