# Generated by Django 6.0.2 on 2026-09-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_seed_text_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ut_method',
            field=models.TextField(blank=True),
        ),
    ]
