# Generated by Django 6.0.2 on 2026-10-01 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0022_ut_method_textfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='acceptance_standard',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_time_check1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_time_check2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_time_initial',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_time_out',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='contractor',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='exam_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='item_description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='report',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='procedure_rev',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
