# Generated by Django 6.0.2 on 2026-10-01 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_weld_form_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pipe_size', models.CharField(blank=True, help_text='For your reference, e.g. 6in Sch 40.', max_length=100)),
                ('thickness', models.FloatField()),
                ('bevel_angle', models.FloatField(default=37.5, help_text='Each side, from vertical.')),
                ('root_gap', models.FloatField(default=0.0625)),
                ('root_face', models.FloatField(default=0.0625)),
                ('cap_width', models.FloatField(blank=True, help_text='Blank = bevel opening plus 1/16" each side.', null=True)),
                ('index_offset', models.FloatField(help_text='Wedge front to weld centre line.')),
                ('exit_point', models.FloatField(default=0.45, help_text='Wedge front back to the beam exit (index) point.')),
                ('wedge_angle', models.FloatField(default=36.0)),
                ('angle_start', models.FloatField(default=45.0)),
                ('angle_stop', models.FloatField(default=70.0)),
                ('angle_step', models.FloatField(default=1.0)),
                ('legs', models.PositiveSmallIntegerField(choices=[(1, 'First leg only'), (2, 'First and second leg')], default=2)),
                ('sides', models.CharField(choices=[('both', 'Both sides of the weld'), ('one', 'One side')], default='both', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='scan_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.scanplan'),
        ),
    ]
