# Generated by Django 6.0.2 on 2026-10-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_seed_catalogues'),
        ('reports', '0024_scan_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplan',
            name='aperture_elements',
            field=models.PositiveIntegerField(blank=True, help_text='Blank = all elements.', null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='first_element',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='probe_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_plans', to='equipment.probemodel', verbose_name='Probe'),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='sensitivity_block',
            field=models.ForeignKey(blank=True, help_text="Fills thickness, pipe size, bevel and velocity, and the weld report's Material Information.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_plans', to='equipment.sensitivityblock'),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='shear_velocity',
            field=models.FloatField(default=0.1276, help_text='Part shear velocity, in/µs.'),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='wedge_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_plans', to='equipment.wedgemodel', verbose_name='Wedge'),
        ),
    ]
