# Generated by Django 6.0.2 on 2026-10-01 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_probe_model_ordering'),
        ('reports', '0025_scan_plan_catalogue_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='aperture_elements',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Aperture (elements)'),
        ),
        migrations.AddField(
            model_name='setup',
            name='catalogue_probe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setups', to='equipment.probemodel', verbose_name='Catalogue probe'),
        ),
        migrations.AddField(
            model_name='setup',
            name='catalogue_wedge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='setups', to='equipment.wedgemodel', verbose_name='Catalogue wedge'),
        ),
        migrations.AddField(
            model_name='setup',
            name='first_element',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
