# Generated by Django 6.0.2 on 2026-10-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0026_setup_catalogue_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanplan',
            name='angle_start',
            field=models.FloatField(default=40.0),
        ),
    ]
