# Generated by Django 6.0.2 on 2026-10-01 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0027_scan_plan_start_angle_40'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='index_offset',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='scanplan',
            name='index_offset',
            field=models.FloatField(blank=True, help_text='Wedge front to weld centre line. Blank = the weld toe (half the cap width).', null=True),
        ),
    ]
