# Generated by Django 6.0.2 on 2026-10-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_index_offset_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplan',
            name='units',
            field=models.CharField(choices=[('imperial', 'Imperial (in)'), ('metric', 'Metric (mm)')], default='imperial', max_length=10),
        ),
        migrations.AddField(
            model_name='setup',
            name='units',
            field=models.CharField(choices=[('imperial', 'Imperial (in)'), ('metric', 'Metric (mm)')], default='imperial', max_length=10),
        ),
        migrations.AddField(
            model_name='setup',
            name='weld_bevel_angle',
            field=models.CharField(blank=True, max_length=20, verbose_name='Bevel angle (°)'),
        ),
        migrations.AddField(
            model_name='setup',
            name='weld_cap_width',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cap width'),
        ),
        migrations.AddField(
            model_name='setup',
            name='weld_root_face',
            field=models.CharField(blank=True, max_length=20, verbose_name='Root face (land)'),
        ),
        migrations.AddField(
            model_name='setup',
            name='weld_root_gap',
            field=models.CharField(blank=True, max_length=20, verbose_name='Root gap'),
        ),
    ]
