# Generated by Django 6.0.2 on 2026-10-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_units_and_weld_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplan',
            name='wedge_first_element_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='wedge_primary_offset',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='wedge_velocity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='wedge_first_element_height',
            field=models.FloatField(blank=True, null=True, verbose_name='First element height (mm)'),
        ),
        migrations.AddField(
            model_name='setup',
            name='wedge_primary_offset',
            field=models.FloatField(blank=True, null=True, verbose_name='Wedge primary offset (mm)'),
        ),
        migrations.AddField(
            model_name='setup',
            name='wedge_velocity',
            field=models.FloatField(blank=True, null=True, verbose_name='Wedge velocity (m/s)'),
        ),
    ]
