# Generated by Django 6.0.2 on 2026-10-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_nde_wedge_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplan',
            name='wedge_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='wedge_length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='wedge_height',
            field=models.FloatField(blank=True, null=True, verbose_name='Wedge height (mm)'),
        ),
        migrations.AddField(
            model_name='setup',
            name='wedge_length',
            field=models.FloatField(blank=True, null=True, verbose_name='Wedge length (mm)'),
        ),
    ]
