# Generated by Django 6.0.2 on 2026-10-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_scan_plan_skews'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='amplitude_range',
            field=models.CharField(blank=True, max_length=50, verbose_name='Amplitude range'),
        ),
        migrations.AddField(
            model_name='setup',
            name='analysis_software',
            field=models.CharField(blank=True, max_length=100, verbose_name='Analysis software'),
        ),
        migrations.AddField(
            model_name='setup',
            name='analysis_software_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Analysis software version'),
        ),
        migrations.AddField(
            model_name='setup',
            name='cable_length',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cable length'),
        ),
        migrations.AddField(
            model_name='setup',
            name='cable_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cable type'),
        ),
        migrations.AddField(
            model_name='setup',
            name='couplant',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='setup',
            name='exam_surface',
            field=models.CharField(blank=True, max_length=50, verbose_name='Exam surface (ID / OD)'),
        ),
        migrations.AddField(
            model_name='setup',
            name='focal_plane',
            field=models.CharField(blank=True, max_length=50, verbose_name='Focal plane'),
        ),
        migrations.AddField(
            model_name='setup',
            name='module_cal_due',
            field=models.CharField(blank=True, max_length=50, verbose_name='Module cal. due'),
        ),
        migrations.AddField(
            model_name='setup',
            name='module_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Module model'),
        ),
        migrations.AddField(
            model_name='setup',
            name='module_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Module S/N'),
        ),
        migrations.AddField(
            model_name='setup',
            name='points_quantity',
            field=models.CharField(blank=True, max_length=50, verbose_name='Points quantity'),
        ),
        migrations.AddField(
            model_name='setup',
            name='scan_speed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Scan speed'),
        ),
        migrations.AddField(
            model_name='setup',
            name='scanner_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Scanner make / model'),
        ),
        migrations.AddField(
            model_name='setup',
            name='scanner_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Scanner type'),
        ),
        migrations.AddField(
            model_name='setup',
            name='scanning_db',
            field=models.CharField(blank=True, max_length=50, verbose_name='Scanning dB'),
        ),
        migrations.AddField(
            model_name='setup',
            name='scope_cal_due',
            field=models.CharField(blank=True, max_length=50, verbose_name='Instrument cal. due'),
        ),
        migrations.AddField(
            model_name='setup',
            name='smoothing',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='setup',
            name='software_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Software version'),
        ),
        migrations.AddField(
            model_name='setup',
            name='time_base',
            field=models.CharField(blank=True, max_length=100, verbose_name='Time base start / stop'),
        ),
        migrations.AddField(
            model_name='setup',
            name='transfer_db',
            field=models.CharField(blank=True, max_length=50, verbose_name='Transfer dB'),
        ),
        migrations.AddField(
            model_name='setup',
            name='wedge_curve',
            field=models.CharField(blank=True, max_length=50, verbose_name='Wedge curve type'),
        ),
        migrations.AddField(
            model_name='setup',
            name='wedge_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Wedge material'),
        ),
    ]
