# Generated by Django 6.0.2 on 2026-10-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0033_weld_form_equipment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, unique=True)),
                ('report_values', models.JSONField(blank=True, default=dict)),
                ('setup_values', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
