# Generated by Django 6.0.2 on 2026-10-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0034_report_defaults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportdefaults',
            options={'ordering': ['report_type', 'name']},
        ),
        migrations.AddField(
            model_name='reportdefaults',
            name='in_use',
            field=models.BooleanField(default=False, verbose_name='Used for new reports'),
        ),
        migrations.AddField(
            model_name='reportdefaults',
            name='name',
            field=models.CharField(default='Standard', max_length=100),
        ),
        migrations.AlterField(
            model_name='reportdefaults',
            name='report_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='reportdefaults',
            constraint=models.UniqueConstraint(fields=('report_type', 'name'), name='unique_defaults_name_per_type'),
        ),
        migrations.AddConstraint(
            model_name='reportdefaults',
            constraint=models.UniqueConstraint(condition=models.Q(('in_use', True)), fields=('report_type',), name='one_defaults_in_use_per_type'),
        ),
    ]
