# Generated by Django 6.0.2 on 2026-10-02 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_probe_model_ordering'),
        ('reports', '0035_named_default_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='inst_analysis_software',
            field=models.CharField(blank=True, max_length=100, verbose_name='Analysis software'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_analysis_software_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Analysis software version'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_cal_due',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cal. due date'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_encoder_cal',
            field=models.CharField(blank=True, max_length=100, verbose_name='Encoder cal. (steps/in)'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_manufacturer',
            field=models.CharField(blank=True, max_length=100, verbose_name='Manufacturer'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_module_cal_due',
            field=models.CharField(blank=True, max_length=50, verbose_name='Module cal. due date'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_module_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Module model'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_module_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Module S/N'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Testing instrument'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_scan_res',
            field=models.CharField(blank=True, max_length=50, verbose_name='Scan res. (in)'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_scan_speed',
            field=models.CharField(blank=True, max_length=50, verbose_name='Speed (in/sec)'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_scanner_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Scanner make / model'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_scanner_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Scanner type'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='S/N'),
        ),
        migrations.AddField(
            model_name='report',
            name='inst_software_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Software version'),
        ),
        migrations.CreateModel(
            name='ReportProbe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, help_text='Column heading, e.g. 90°, 270°, 0°, Trans.', max_length=50)),
                ('kind', models.CharField(choices=[('paut', 'PAUT'), ('conv_long', '0° L-wave (conventional)'), ('conv_shear', 'SW conventional')], default='paut', max_length=20)),
                ('make', models.CharField(blank=True, max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=50)),
                ('cable_type', models.CharField(blank=True, max_length=100)),
                ('cable_length', models.CharField(blank=True, max_length=50)),
                ('serial', models.CharField(blank=True, max_length=100, verbose_name='Probe S/N')),
                ('wedge_material', models.CharField(blank=True, max_length=100, verbose_name="Wedge mat'l")),
                ('wedge_model', models.CharField(blank=True, max_length=100)),
                ('wedge_angle', models.CharField(blank=True, max_length=50, verbose_name='Wedge ref. angle')),
                ('wedge_diameter', models.CharField(blank=True, max_length=50, verbose_name='Wedge dia.')),
                ('wedge_curve', models.CharField(blank=True, max_length=50, verbose_name='Wedge curve type')),
                ('probe_check', models.CharField(blank=True, max_length=50)),
                ('wedge_primary_offset', models.FloatField(blank=True, null=True)),
                ('wedge_first_element_height', models.FloatField(blank=True, null=True)),
                ('wedge_velocity', models.FloatField(blank=True, null=True)),
                ('wedge_length', models.FloatField(blank=True, null=True)),
                ('wedge_height', models.FloatField(blank=True, null=True)),
                ('catalogue_probe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_probes', to='equipment.probemodel', verbose_name='Catalogue probe')),
                ('catalogue_wedge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_probes', to='equipment.wedgemodel', verbose_name='Catalogue wedge')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='probes', to='reports.report')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ReportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('label', models.CharField(blank=True, help_text='Column heading, e.g. 0°, Trans.', max_length=50)),
                ('scan', models.CharField(blank=True, max_length=50)),
                ('wave_mode', models.CharField(blank=True, max_length=50)),
                ('angles', models.CharField(blank=True, max_length=50, verbose_name='Angle(s)')),
                ('elements', models.CharField(blank=True, max_length=50, verbose_name='Ele start / stop')),
                ('angle_increment', models.CharField(blank=True, max_length=50)),
                ('vpa', models.CharField(blank=True, max_length=50, verbose_name='Ele per VPA / VPA index')),
                ('focal_plane', models.CharField(blank=True, max_length=50)),
                ('focal_distance', models.CharField(blank=True, max_length=50)),
                ('time_base', models.CharField(blank=True, max_length=100, verbose_name='Time base, start / stop')),
                ('voltage', models.CharField(blank=True, max_length=50, verbose_name='Pulser voltage')),
                ('points_quantity', models.CharField(blank=True, max_length=50)),
                ('smoothing', models.CharField(blank=True, max_length=50)),
                ('filter', models.CharField(blank=True, max_length=50, verbose_name='Filter settings')),
                ('amplitude_range', models.CharField(blank=True, max_length=50)),
                ('reference_db', models.CharField(blank=True, max_length=50, verbose_name='Reference dB')),
                ('transfer_db', models.CharField(blank=True, max_length=50, verbose_name='Transfer dB')),
                ('scanning_db', models.CharField(blank=True, max_length=50, verbose_name='Scanning dB')),
                ('first_element', models.PositiveIntegerField(blank=True, null=True)),
                ('aperture_elements', models.PositiveIntegerField(blank=True, null=True, verbose_name='Aperture (elements)')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='reports.report')),
                ('probe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='reports.reportprobe')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
