# Generated by Django 6.0.2 on 2026-10-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0037_weld_setups_to_grid'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdefaults',
            name='group_values',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='reportdefaults',
            name='probe_values',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
