# Generated by Django 6.0.2 on 2026-10-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0039_default_columns_source_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportgroup',
            name='not_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reportprobe',
            name='kind',
            field=models.CharField(choices=[('paut', 'PAUT'), ('conv_long', '0° L-wave (conventional)'), ('conv_shear', 'SW conventional'), ('na', 'N/A')], default='paut', max_length=20),
        ),
    ]
