# Generated by Django 6.0.2 on 2026-10-02 15:31

"""
The weld form's technician and reviewer lines become report fields; existing weld reports take
them from their people (examined, else prepared; reviewed), as the Excel output did.
"""
from django.db import migrations, models


def people_to_fields(apps, schema_editor):
    Report = apps.get_model('reports', 'Report')
    for report in Report.objects.filter(report_type='paut_weld'):
        people = list(report.people.order_by('order', 'pk'))
        first = lambda role: next((p for p in people if getattr(p, role)), None)
        technician = first('examined') or first('prepared')
        reviewer = first('reviewed')
        if technician:
            report.weld_technician, report.weld_technician_cert = technician.name, technician.certification
        if reviewer:
            report.weld_reviewer, report.weld_reviewer_cert = reviewer.name, reviewer.certification
        if technician or reviewer:
            report.save()


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_not_applicable_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='weld_reviewer',
            field=models.CharField(blank=True, max_length=200, verbose_name='Reviewed by'),
        ),
        migrations.AddField(
            model_name='report',
            name='weld_reviewer_cert',
            field=models.CharField(blank=True, max_length=200, verbose_name='Reviewer certification'),
        ),
        migrations.AddField(
            model_name='report',
            name='weld_technician',
            field=models.CharField(blank=True, max_length=200, verbose_name='Technician'),
        ),
        migrations.AddField(
            model_name='report',
            name='weld_technician_cert',
            field=models.CharField(blank=True, max_length=200, verbose_name='Technician certification'),
        ),
        migrations.RunPython(people_to_fields, migrations.RunPython.noop),
    ]
