# Generated by Django 6.0.2 on 2026-10-02 15:13
"""
Accept calibration: existing weld reports printed Accept on each calibration row with a time,
so they start with it ticked.
"""

from django.db import migrations, models


def accept_existing(apps, schema_editor):
    apps.get_model('reports', 'Report').objects.filter(report_type='paut_weld').update(cal_accept=True)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0040_not_applicable_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='cal_accept',
            field=models.BooleanField(default=False, verbose_name='Accept calibration'),
        ),
        migrations.RunPython(accept_existing, migrations.RunPython.noop),
    ]
