# Generated by Django 6.0.2 on 2026-10-02 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_inventory_sheet_fields'),
        ('reports', '0041_weld_personnel'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='add1_block_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 block type'),
        ),
        migrations.AddField(
            model_name='report',
            name='add1_diameter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 diameter'),
        ),
        migrations.AddField(
            model_name='report',
            name='add1_exam_surface',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 exam surface (i.d. / o.d.)'),
        ),
        migrations.AddField(
            model_name='report',
            name='add1_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 material'),
        ),
        migrations.AddField(
            model_name='report',
            name='add1_sch_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 sch / nom. thk'),
        ),
        migrations.AddField(
            model_name='report',
            name='add1_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 block s/n'),
        ),
        migrations.AddField(
            model_name='report',
            name='add1_surface',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 surface condition'),
        ),
        migrations.AddField(
            model_name='report',
            name='add1_temp',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 temp (°f)'),
        ),
        migrations.AddField(
            model_name='report',
            name='add1_vel_long',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 velocity l-wave'),
        ),
        migrations.AddField(
            model_name='report',
            name='add1_vel_shear',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 1 velocity shear'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_block_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 block type'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_diameter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 diameter'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_exam_surface',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 exam surface (i.d. / o.d.)'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 material'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_sch_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 sch / nom. thk'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 block s/n'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_surface',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 surface condition'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_temp',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 temp (°f)'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_vel_long',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 velocity l-wave'),
        ),
        migrations.AddField(
            model_name='report',
            name='add2_vel_shear',
            field=models.CharField(blank=True, max_length=100, verbose_name='Additional block 2 velocity shear'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_bevel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. bevel geometry'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_block_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. block type'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_couplant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. couplant'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_diameter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. diameter'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_exam_surface',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. exam surface (i.d. / o.d.)'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. material'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_sch_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. sch / nom. thk'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_serial',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. s/n'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_surface',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. surface condition'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_temp',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. temp (°f)'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_vel_long',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. velocity l-wave'),
        ),
        migrations.AddField(
            model_name='report',
            name='cal_std_vel_shear',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cal. Std. velocity shear'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_bevel',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected bevel geometry'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_block_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected block type'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_couplant',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected couplant'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_diameter',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected diameter'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_exam_surface',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected exam surface (i.d. / o.d.)'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected material'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_sch_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected sch / nom. thk'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_surface',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected surface condition'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_temp',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected temp (°f)'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_vel_long',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected velocity l-wave'),
        ),
        migrations.AddField(
            model_name='report',
            name='item_vel_shear',
            field=models.CharField(blank=True, max_length=100, verbose_name='Item inspected velocity shear'),
        ),
        migrations.AddField(
            model_name='report',
            name='pipe_size',
            field=models.CharField(blank=True, max_length=100, verbose_name='NPS / Sch'),
        ),
        migrations.AddField(
            model_name='report',
            name='scan_part',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sensitivity_block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='equipment.sensitivityblock'),
        ),
        migrations.AddField(
            model_name='report',
            name='tcg_amplitude',
            field=models.CharField(blank=True, max_length=100, verbose_name='Amplitude'),
        ),
        migrations.AddField(
            model_name='report',
            name='tcg_block',
            field=models.CharField(blank=True, max_length=100, verbose_name='TCG block used'),
        ),
        migrations.AddField(
            model_name='report',
            name='tcg_ref_block',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ref block used'),
        ),
        migrations.AddField(
            model_name='report',
            name='tcg_reflector',
            field=models.CharField(blank=True, max_length=100, verbose_name='Reflector type'),
        ),
        migrations.AddField(
            model_name='report',
            name='tcg_thickness',
            field=models.CharField(blank=True, max_length=100, verbose_name='Block thickness (T)'),
        ),
    ]
