# Generated by Django 6.0.2 on 2026-10-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0042_sensitivity_block_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportimage',
            name='kind',
            field=models.CharField(choices=[('scan', 'Scan image (photo summary)'), ('drawing', 'Equipment drawing'), ('indication', 'Indication image (weld form)')], default='scan', max_length=20),
        ),
    ]
