# Generated by Django 6.0.2 on 2026-10-05 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0043_indication_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplan',
            name='haz_width',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='mode',
            field=models.CharField(choices=[('simple', 'Simple'), ('advanced', 'Advanced')], default='simple', max_length=10),
        ),
    ]
