# Generated by Django 6.0.2 on 2026-10-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0044_scan_plan_mode_haz'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplan',
            name='bevel_side',
            field=models.PositiveSmallIntegerField(choices=[(90, '90° side'), (270, '270° side')], default=270),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='bottom_bevel_angle',
            field=models.FloatField(default=37.5),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='cap_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='counterbore_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='counterbore_length',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='counterbore_taper',
            field=models.FloatField(default=30.0),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='land_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='root_height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='root_radius',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='transition_height',
            field=models.FloatField(default=0.75),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='upper_bevel_angle',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='weld_type',
            field=models.CharField(choices=[('single_v', 'Single V'), ('double_v', 'Double V'), ('single_bevel', 'Single bevel'), ('j_bevel', 'J bevel'), ('u_groove', 'U groove'), ('compound', 'Compound bevel')], default='single_v', max_length=20),
        ),
    ]
