# Generated by Django 6.0.2 on 2026-10-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0045_scan_plan_weld_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplan',
            name='beam_direction',
            field=models.CharField(choices=[('axial', 'Axial (girth weld)'), ('circumferential', 'Circumferential (long seam)')], default='axial', max_length=20),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='outside_diameter',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='wedge_contour',
            field=models.CharField(choices=[('flat', 'Flat'), ('contoured', 'Contoured to the OD')], default='flat', max_length=10),
        ),
    ]
