# Generated by Django 6.0.2 on 2026-10-05 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0046_scan_plan_curvature'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanplan',
            name='print_reflectors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scanplan',
            name='reflectors',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
