# Generated by Django 6.0.2 on 2026-10-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0047_scan_plan_reflectors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='As job folder names start, e.g. FHR.', max_length=6, unique=True)),
                ('client', models.CharField(help_text="The report's Client, e.g. Flint Hills Resources.", max_length=200)),
                ('location', models.CharField(blank=True, help_text="The report's Location; blank keeps the defaults'.", max_length=200)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='job_folder',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='report',
            name='job_folder_files',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
