# Generated by Django 6.0.2 on 2026-10-06 15:10

import os

from django.conf import settings
from django.db import migrations, models


def carry_over_jobs_root(apps, schema_editor):
    """The weld jobs folder set in the app (else settings.WELD_JOBS_DIR, when it's there) is the weld reports' default."""
    AppSetting = apps.get_model('reports', 'AppSetting')
    WorkingFolder = apps.get_model('reports', 'WorkingFolder')
    setting = AppSetting.objects.filter(key='jobs_root').first()
    path = setting.value if setting and setting.value else str(settings.WELD_JOBS_DIR)
    if setting or os.path.isdir(path):
        WorkingFolder.objects.create(path=path, report_type='paut_weld', is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0049_seed_client_codes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkingFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text='The full path, e.g. C:\\Users\\…\\Desktop\\Reports\\001 Welds.', max_length=500)),
                ('report_type', models.CharField(help_text='The reports whose job folders are kept here.', max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Opened first for this report type.', verbose_name='Default')),
            ],
            options={
                'ordering': ['report_type', '-is_default', 'path'],
            },
        ),
        migrations.RunPython(carry_over_jobs_root, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='AppSetting',
        ),
    ]
