# Generated by Django 6.0.2 on 2026-10-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0050_working_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportimage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='setup',
            name='inspection_material',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='setup',
            name='inspection_temp',
            field=models.CharField(blank=True, max_length=50, verbose_name='Inspection temperature'),
        ),
    ]
