# Generated by Django 6.0.2 on 2026-10-06 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0051_corrosion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='nde_sheet',
            field=models.TextField(blank=True),
        ),
    ]
