# Generated by Django 6.0.2 on 2026-10-08 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0052_setup_nde_sheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='method_description',
            field=models.ForeignKey(blank=True, help_text='A Text library technique description; add one there for a method not listed.', limit_choices_to={'kind': 'technique'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='reports.textsnippet'),
        ),
    ]
