# Generated by Django 6.0.2 on 2026-10-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0054_short_form_method_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='issued_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued')], default='draft', max_length=10),
        ),
    ]
