# Generated by Django 6.0.2 on 2026-10-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0055_report_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The equipment number, e.g. 11V-9.', max_length=100)),
                ('service', models.CharField(blank=True, help_text='e.g. Preflash Tower Overhead Accumulator.', max_length=200)),
                ('vessel_type', models.CharField(choices=[('horizontal', 'Horizontal vessel / drum'), ('vertical', 'Vertical vessel / tower'), ('exchanger', 'Shell & tube exchanger'), ('tank', 'Storage tank')], default='horizontal', max_length=20, verbose_name='Type')),
                ('units', models.CharField(choices=[('imperial', 'Imperial (ft-in)'), ('metric', 'Metric (mm)')], default='imperial', max_length=10)),
                ('diameter', models.FloatField(help_text="The shell's diameter; a course can have its own (a tower's top section).")),
                ('diameter_basis', models.CharField(choices=[('ID', 'ID'), ('OD', 'OD')], default='ID', max_length=2, verbose_name='Measured')),
                ('start_head', models.CharField(choices=[('ellipsoidal', '2:1 ellipsoidal'), ('hemispherical', 'Hemispherical'), ('torispherical', 'F&D (torispherical)'), ('flat', 'Flat / blind cover'), ('cone', 'Cone'), ('dome', 'Dome roof')], default='ellipsoidal', max_length=20)),
                ('end_head', models.CharField(choices=[('ellipsoidal', '2:1 ellipsoidal'), ('hemispherical', 'Hemispherical'), ('torispherical', 'F&D (torispherical)'), ('flat', 'Flat / blind cover'), ('cone', 'Cone'), ('dome', 'Dome roof')], default='ellipsoidal', max_length=20)),
                ('courses', models.JSONField(blank=True, default=list)),
                ('nozzles', models.JSONField(blank=True, default=list)),
                ('supports', models.CharField(choices=[('auto', 'Usual for the type'), ('saddles', 'Saddles'), ('skirt', 'Skirt'), ('legs', 'Legs'), ('none', 'None')], default='auto', max_length=10)),
                ('view_from', models.CharField(choices=[('N', 'N'), ('NE', 'NE'), ('E', 'E'), ('SE', 'SE'), ('S', 'S'), ('SW', 'SW'), ('W', 'W'), ('NW', 'NW')], default='S', help_text="Where you stand to see the drawing: seen from the S, a horizontal vessel's left end is W and a tower's right-hand side is E.", max_length=2, verbose_name='Viewed from')),
                ('seam_start', models.PositiveIntegerField(default=1, help_text='Seams are numbered from the start end on, from this number.', verbose_name='First seam number')),
                ('boot_diameter', models.FloatField(blank=True, null=True)),
                ('boot_length', models.FloatField(blank=True, null=True)),
                ('boot_position', models.FloatField(blank=True, help_text="From the left tangent line to the boot's centre.", null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
