# Generated by Django 6.0.2 on 2026-10-09 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0056_vessel'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='vessel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.vessel'),
        ),
        migrations.AddField(
            model_name='report',
            name='vessel_caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='report',
            name='vessel_coverage',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
