# Generated by Django 6.0.2 on 2026-10-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('procedure', 'Procedures'), ('code', 'Code Material'), ('training', 'Training Material')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(max_length=255, upload_to='documents/%Y/')),
                ('notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
