# Generated by Django 6.0.2 on 2026-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
