# Generated by Django 6.0.2 on 2026-10-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_last_opened_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.CharField(choices=[('procedure', 'Procedures'), ('code', 'Code Material'), ('training', 'Training Material'), ('form', 'Report Forms')], max_length=20),
        ),
    ]
