# Generated by Django 6.0.2 on 2026-10-09 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='revision',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=255, upload_to='documents/%Y/')),
                ('revision', models.CharField(blank=True, max_length=50)),
                ('replaced_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='documents.document')),
            ],
            options={
                'ordering': ['-replaced_at', '-pk'],
            },
        ),
    ]
