# Generated by Django 6.0.2 on 2026-10-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(db_index=True, max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('group', models.IntegerField(default=0)),
                ('number', models.PositiveIntegerField(help_text="Numbered per file, like OmniPC's #.")),
                ('scan', models.IntegerField()),
                ('lateral', models.IntegerField(help_text='Beam or index line.')),
                ('scan_position', models.FloatField(blank=True, null=True)),
                ('index_position', models.FloatField(blank=True, null=True)),
                ('angle', models.FloatField(blank=True, null=True)),
                ('gain', models.FloatField(default=0)),
                ('readings', models.JSONField(blank=True, default=dict)),
                ('cursors', models.JSONField(blank=True, default=dict)),
                ('sizing', models.JSONField(blank=True, default=dict)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['file_path', 'number'],
            },
        ),
    ]
