# Generated by Django 6.0.2 on 2026-10-08 18:22

import django.db.models.deletion
from django.db import migrations, models

# The search index's full-text table (assistant/index.py): SQLite FTS5
FTS_TABLE = ("CREATE VIRTUAL TABLE IF NOT EXISTS assistant_search USING fts5("
             "kind UNINDEXED, object_id UNINDEXED, page UNINDEXED, title, body, tokenize='porter unicode61')")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='anthropic', max_length=30)),
                ('model', models.CharField(default='claude-haiku-4-5', max_length=100)),
                ('api_key_encrypted', models.TextField(blank=True)),
                ('monthly_cap', models.DecimalField(blank=True, decimal_places=2, help_text='The chat stops for the month when its estimated spend reaches this. Blank = no cap.', max_digits=8, null=True, verbose_name='Monthly spending cap (USD)')),
                ('model_list', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'assistant settings',
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('provider', models.CharField(default='anthropic', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='IndexedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('fingerprint', models.CharField(max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('kind', 'object_id'), name='assistant_indexed_item_unique')],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('answer_html', models.TextField(blank=True)),
                ('status', models.CharField(default='ok', max_length=10)),
                ('provider', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('cache_read_tokens', models.PositiveIntegerField(default=0)),
                ('cache_write_tokens', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='assistant.conversation')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.RunSQL(FTS_TABLE, 'DROP TABLE IF EXISTS assistant_search'),
    ]
