# Generated by Django 6.0.2 on 2026-10-08 18:58

from django.db import migrations, models


def copy_key_and_models(apps, schema_editor):
    """The single Anthropic key and model list become the per-provider ones."""
    Settings = apps.get_model('assistant', 'AssistantSettings')
    for settings in Settings.objects.all():
        if settings.api_key_encrypted:
            settings.api_keys = {'anthropic': settings.api_key_encrypted}
        if settings.model_list:
            settings.model_lists = {'anthropic': settings.model_list}
        settings.save()


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistantsettings',
            name='api_keys',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='input_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Input price (USD per million tokens)'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='model_lists',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='ollama_url',
            field=models.CharField(default='http://localhost:11434', max_length=200, verbose_name='Ollama address'),
        ),
        migrations.AddField(
            model_name='assistantsettings',
            name='output_price',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Output price (USD per million tokens)'),
        ),
        migrations.RunPython(copy_key_and_models, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='assistantsettings',
            name='api_key_encrypted',
        ),
        migrations.RemoveField(
            model_name='assistantsettings',
            name='model_list',
        ),
    ]
