# Generated by Django 6.0.2 on 2026-10-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_per_provider_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexeditem',
            name='stamp',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
